### ISSUE TITLE
some configurations fail to be dumped (duplicate template entries)

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/web-confdb#19]
Some configurations cannot be dumped, due to duplicate keys in the table that associates the modules (path items) to their templates.

One such configuration is `/dev/CMSSW_7_1_1/AlternativeTrackingScenarios/GRun_TK1B/V23`, failing with
```
[2015-12-16 15:47:35,658 - ERROR/PoolWorker-1] multiprocessing: ERROR: getModules: error:
(cx_Oracle.DatabaseError) ORA-01427: single-row subquery returns more than one row

[2015-12-16 15:47:35,665 - CRITICAL/MainProcess] multiprocessing: Traceback (most recent call last):
  File "/data/user/fwyzard/ConfDB/src/web-confdb/Server/Application_py266/converter/task.py", line 48, in worker
    data = getattr(databuilder, method)()
  File "/data/user/fwyzard/ConfDB/src/web-confdb/Server/Application_py266/converter/data_builder.py", line 293, in getModules
    modules = self.queries.getModules(self.version.id, self.database, self.logger)
  File "/data/user/fwyzard/ConfDB/src/web-confdb/Server/Application_py266/confdb_queries/confdb_queries.py", line 1217, in getModules
    elements = query.all()
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2423, in all
    return list(self)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2571, in __iter__
    return self._execute_and_instances(context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/orm/query.py", line 2586, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "build/bdist.linux-x86_64/egg/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "build/bdist.linux-x86_64/egg/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (cx_Oracle.DatabaseError) ORA-01427: single-row subquery returns more than one row
 [SQL: 'SELECT (SELECT u_mod2templ.id_templ \nFROM u_mod2templ \nWHERE u_mod2templ.id_pae = u_paelements.id) AS anon_1, (SELECT u_moduletemplates.name \nFROM u_moduletemplates, u_mod2templ \nWHERE u_moduletemplates.id = u_mod2templ.id_templ AND u_mod2templ.id_pae = u_paelements.id) AS anon_2, (SELECT u_moduletypes.type \nFROM u_moduletypes, u_moduletemplates, u_mod2templ \nWHERE u_moduletypes.id = u_moduletemplates.id_mtype AND u_moduletemplates.id = u_mod2templ.id_templ AND u_mod2templ.id_pae = u_paelements.id) AS anon_3, u_paelements.id AS u_paelements_id, u_paelements.name AS u_paelements_name, u_paelements.paetype AS u_paelements_paetype \nFROM u_paelements, u_pathid2pae, u_pathid2conf \nWHERE u_paelements.paetype = :paetype_1 AND u_paelements.id = u_pathid2pae.id_pae AND u_pathid2pae.id_pathid = u_pathid2conf.id_pathid AND u_pathid2conf.id_confver = :id_confver_1'] [parameters: {'id_confver_1': 7178, 'paetype_1': 1}]

[2015-12-16 15:47:35,665 - INFO/MainProcess] multiprocessing: process shutting down
```

**Comment by fwyzard** [comment]
And here's the query in a more readable format:
```sql
SELECT 
    ( SELECT u_mod2templ.id_templ FROM u_mod2templ WHERE u_mod2templ.id_pae = u_paelements.id ) AS id_templ, 
    ( SELECT u_moduletemplates.name FROM u_moduletemplates, u_mod2templ WHERE u_moduletemplates.id = u_mod2templ.id_templ AND u_mod2templ.id_pae = u_paelements.id ) AS name, 
    ( SELECT u_moduletypes.type FROM u_moduletypes, u_moduletemplates, u_mod2templ WHERE u_moduletypes.id = u_moduletemplates.id_mtype AND u_moduletemplates.id = u_mod2templ.id_templ AND u_mod2templ.id_pae = u_paelements.id ) AS type, 
    u_paelements.id AS u_paelements_id, 
    u_paelements.name AS u_paelements_name, 
    u_paelements.paetype AS u_paelements_paetype 
FROM 
    u_paelements, 
    u_pathid2pae, 
    u_pathid2conf 
WHERE 
    u_paelements.paetype = 1 
AND u_paelements.id = u_pathid2pae.id_pae 
AND u_pathid2pae.id_pathid = u_pathid2conf.id_pathid 
AND u_pathid2conf.id_confver = 7178;
```
